useTabs: false
tabWidth: 4
semi: true
singleQuote: false
trailingComma: none
bracketSpacing: true
arrowParens: avoid

overrides:
  - files: "*.html"
    options:
      parser: "html"
      tabWidth: 2
  - files: "*.component.html"
    options:
      parser: "angular"
