extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss
  - stylelint-prettier/recommended

plugins:
  - stylelint-prettier

rules:
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - "tailwind"
        - "apply"
        - "layer"
