name: Deploy Workflow

on:
  push:
    branches:
      - release

env:
  REGISTRY: ghcr.io
  NEXT_PUBLIC_MEILISEARCH_HOST: https://meilisearch.red4ext.com
  NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY: e6a5388911f23ef86826a69db339dbd58051bbd91896e60037274ebe7f1cf43b

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create environment variables
        run: |
          echo IMAGE_NAME=${GITHUB_REPOSITORY,,} >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          build-args: |
            MEILISEARCH_HOST=${{ env.NEXT_PUBLIC_MEILISEARCH_HOST }}
            MEILISEARCH_PUBLIC_KEY=${{ env.NEXT_PUBLIC_MEILISEARCH_PUBLIC_KEY }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update_search_engine:
    name: Update the search-engine
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install packages
        run: npm install

      - name: Indexing
        env:
          MEILISEARCH_PRIVATE_KEY: ${{ secrets.MEILISEARCH_PRIVATE_KEY }}

        run: npm run index-natives
